// AppButton — Jetpack Compose
//
// Generated by /generate-component using the project's design token system.
// Platform: Android (Kotlin + Jetpack Compose)
// Tokens: app/src/main/java/com/yourapp/ui/theme/Tokens.kt

package com.yourapp.ui.components

import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.sizeIn
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.disabled
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.yourapp.ui.theme.AppColors
import com.yourapp.ui.theme.AppRadius
import com.yourapp.ui.theme.AppSpacing
import com.yourapp.ui.theme.AppTypography

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/** Visual style variants for [AppButton]. */
enum class AppButtonVariant {
    /** The primary action on a screen — use once per context. */
    Primary,

    /** Supporting action with outlined appearance. */
    Secondary,

    /** Tertiary action; no background or border. */
    Ghost,

    /** Irreversible or dangerous action (delete, remove, clear). */
    Destructive,
}

/** Size options for [AppButton]. */
enum class AppButtonSize { Sm, Md, Lg }

// ─────────────────────────────────────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A design-system-aware button component for Jetpack Compose.
 *
 * All colors, spacing, and radii come from the token system (Tokens.kt).
 * Enforces Material Design minimum touch target of 48×48dp automatically.
 *
 * @param label Visible text and TalkBack content description.
 * @param onClick Click handler.
 * @param modifier Optional layout modifier.
 * @param variant Visual style. Defaults to [AppButtonVariant.Primary].
 * @param size Button size. Defaults to [AppButtonSize.Md].
 * @param enabled Whether the button is interactive. Defaults to `true`.
 * @param isLoading When `true`, shows a spinner in place of the label.
 */
@Composable
fun AppButton(
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    variant: AppButtonVariant = AppButtonVariant.Primary,
    size: AppButtonSize = AppButtonSize.Md,
    enabled: Boolean = true,
    isLoading: Boolean = false,
) {
    val isInteractive = enabled && !isLoading

    // Base modifier: minimum touch target (Material Design: 48×48dp) + semantics
    val baseModifier = modifier
        .sizeIn(minWidth = 48.dp, minHeight = 48.dp)
        .semantics {
            contentDescription = label
            if (!isInteractive) disabled()
        }

    val contentPadding = resolvePadding(size)
    val content: @Composable () -> Unit = { ButtonContent(label, isLoading, size, variant) }

    when (variant) {
        AppButtonVariant.Primary -> Button(
            onClick = onClick,
            modifier = baseModifier,
            enabled = isInteractive,
            contentPadding = contentPadding,
            colors = ButtonDefaults.buttonColors(
                containerColor = AppColors.Primary,
                disabledContainerColor = AppColors.Primary.copy(alpha = 0.4f),
                contentColor = Color.White,
                disabledContentColor = Color.White.copy(alpha = 0.6f),
            ),
            content = { content() },
        )

        AppButtonVariant.Secondary -> OutlinedButton(
            onClick = onClick,
            modifier = baseModifier,
            enabled = isInteractive,
            contentPadding = contentPadding,
            colors = ButtonDefaults.outlinedButtonColors(
                contentColor = AppColors.Primary,
                disabledContentColor = AppColors.Primary.copy(alpha = 0.4f),
            ),
            border = ButtonDefaults.outlinedButtonBorder.copy(
                brush = androidx.compose.ui.graphics.SolidColor(
                    if (isInteractive) AppColors.Primary else AppColors.Primary.copy(alpha = 0.4f)
                ),
            ),
            content = { content() },
        )

        AppButtonVariant.Ghost -> TextButton(
            onClick = onClick,
            modifier = baseModifier,
            enabled = isInteractive,
            contentPadding = contentPadding,
            colors = ButtonDefaults.textButtonColors(
                contentColor = AppColors.Primary,
                disabledContentColor = AppColors.Primary.copy(alpha = 0.4f),
            ),
            content = { content() },
        )

        AppButtonVariant.Destructive -> Button(
            onClick = onClick,
            modifier = baseModifier,
            enabled = isInteractive,
            contentPadding = contentPadding,
            colors = ButtonDefaults.buttonColors(
                containerColor = AppColors.Danger,
                disabledContainerColor = AppColors.Danger.copy(alpha = 0.4f),
                contentColor = Color.White,
                disabledContentColor = Color.White.copy(alpha = 0.6f),
            ),
            content = { content() },
        )
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal composables and helpers
// ─────────────────────────────────────────────────────────────────────────────

@Composable
private fun ButtonContent(
    label: String,
    isLoading: Boolean,
    size: AppButtonSize,
    variant: AppButtonVariant,
) {
    if (isLoading) {
        val indicatorColor = if (
            variant == AppButtonVariant.Primary || variant == AppButtonVariant.Destructive
        ) Color.White else AppColors.Primary

        CircularProgressIndicator(
            modifier = Modifier
                .size(20.dp)
                .semantics { contentDescription = "Loading" },
            color = indicatorColor,
            strokeWidth = 2.dp,
        )
    } else {
        Text(
            text = label,
            fontSize = when (size) {
                AppButtonSize.Sm -> AppTypography.bodySmall
                AppButtonSize.Md -> AppTypography.body
                AppButtonSize.Lg -> AppTypography.heading
            },
            fontWeight = FontWeight.SemiBold,
        )
    }
}

private fun resolvePadding(size: AppButtonSize): PaddingValues = when (size) {
    AppButtonSize.Sm -> PaddingValues(
        horizontal = AppSpacing.sm,
        vertical = AppSpacing.xs,
    )
    AppButtonSize.Md -> PaddingValues(
        horizontal = AppSpacing.md,
        vertical = AppSpacing.sm,
    )
    AppButtonSize.Lg -> PaddingValues(
        horizontal = AppSpacing.lg,
        vertical = AppSpacing.md,
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// Previews
// ─────────────────────────────────────────────────────────────────────────────

@Preview(showBackground = true)
@Composable
private fun AppButtonPreview() {
    androidx.compose.material3.MaterialTheme {
        androidx.compose.foundation.layout.Column(
            verticalArrangement = androidx.compose.foundation.layout.Arrangement.spacedBy(AppSpacing.sm),
            modifier = Modifier.then(Modifier.then(Modifier))
                .then(Modifier)
                .then(Modifier),
        ) {
            AppButton(label = "Save changes", onClick = {})
            AppButton(label = "Cancel", variant = AppButtonVariant.Secondary, onClick = {})
            AppButton(label = "Learn more", variant = AppButtonVariant.Ghost, onClick = {})
            AppButton(label = "Delete account", variant = AppButtonVariant.Destructive, onClick = {})
            AppButton(label = "Saving", isLoading = true, onClick = {})
            AppButton(label = "Not available", enabled = false, onClick = {})
        }
    }
}

/*
 * Usage Examples:
 *
 * // Primary (default)
 * AppButton(label = "Save changes", onClick = { handleSave() })
 *
 * // Secondary
 * AppButton(
 *     label = "Cancel",
 *     variant = AppButtonVariant.Secondary,
 *     onClick = { handleCancel() }
 * )
 *
 * // Destructive
 * AppButton(
 *     label = "Delete account",
 *     variant = AppButtonVariant.Destructive,
 *     onClick = { handleDelete() }
 * )
 *
 * // Disabled
 * AppButton(label = "Not available", enabled = false, onClick = {})
 *
 * // Loading state
 * AppButton(label = "Saving", isLoading = isSaving, onClick = { handleSave() })
 *
 * // Large size
 * AppButton(label = "Get started", size = AppButtonSize.Lg, onClick = { handleStart() })
 */
