// AppButton — SwiftUI
//
// Generated by /generate-component using the project's design token system.
// Platform: SwiftUI (Swift)
// Tokens: Theme.swift
//
// NOTE: This file requires Theme.swift (generated by /setup-mobile-design-system).
// Theme.swift defines: Color.primary, Color.danger, Color.textOnPrimary,
// Font.bodySmall, Font.body, Font.heading, AppSpacing, AppRadius.

import SwiftUI

// MARK: - Types

/// Visual style variants for AppButton.
enum AppButtonVariant {
    /// The primary action on a screen — use once per context.
    case primary
    /// Supporting action with outlined appearance.
    case secondary
    /// Tertiary action; no background or border.
    case ghost
    /// Irreversible or dangerous action (delete, remove, clear).
    case destructive
}

/// Size options for AppButton.
enum AppButtonSize {
    case sm, md, lg
}

// MARK: - AppButton

/// A design-system-aware button component for SwiftUI.
///
/// All colors, spacing, and radii reference the project token system (Theme.swift).
/// Enforces Apple HIG minimum touch target of 44×44pt automatically.
struct AppButton: View {
    /// Visible label text. Also used as the VoiceOver accessibility label.
    let label: String

    /// Tap action.
    let action: () -> Void

    /// Visual style variant. Defaults to `.primary`.
    var variant: AppButtonVariant = .primary

    /// Size of the button. Defaults to `.md`.
    var size: AppButtonSize = .md

    /// Disables interaction and applies muted appearance.
    var isDisabled: Bool = false

    /// When `true`, replaces the label with a progress indicator.
    var isLoading: Bool = false

    /// Optional VoiceOver hint read after a pause following the label.
    var accessibilityHint: String? = nil

    var body: some View {
        Button(action: action) {
            ZStack {
                if isLoading {
                    ProgressView()
                        .progressViewStyle(
                            CircularProgressViewStyle(tint: foregroundColor)
                        )
                        .frame(width: 20, height: 20)
                        .accessibilityLabel("Loading")
                } else {
                    Text(label)
                        .font(labelFont)
                        .fontWeight(.semibold)
                        .lineLimit(1)
                }
            }
            .padding(contentPadding)
            // Apple HIG minimum touch target: 44×44pt
            .frame(minWidth: 44, minHeight: 44)
        }
        .buttonStyle(AppButtonStyle(variant: variant, isDisabled: isDisabled || isLoading))
        .disabled(isDisabled || isLoading)
        .accessibilityLabel(label)
        .accessibilityHint(accessibilityHint ?? "")
        .accessibilityAddTraits(.isButton)
        .opacity(isDisabled || isLoading ? 0.4 : 1.0)
    }

    // MARK: - Computed properties

    private var foregroundColor: Color {
        switch variant {
        case .primary, .destructive: return Color.textOnPrimary
        case .secondary, .ghost:     return Color.primary
        }
    }

    private var labelFont: Font {
        switch size {
        case .sm: return Font.bodySmall
        case .md: return Font.body
        case .lg: return Font.heading
        }
    }

    private var contentPadding: EdgeInsets {
        switch size {
        case .sm:
            return EdgeInsets(
                top: AppSpacing.xs, leading: AppSpacing.sm,
                bottom: AppSpacing.xs, trailing: AppSpacing.sm
            )
        case .md:
            return EdgeInsets(
                top: AppSpacing.sm, leading: AppSpacing.md,
                bottom: AppSpacing.sm, trailing: AppSpacing.md
            )
        case .lg:
            return EdgeInsets(
                top: AppSpacing.md, leading: AppSpacing.lg,
                bottom: AppSpacing.md, trailing: AppSpacing.lg
            )
        }
    }
}

// MARK: - Button Style

/// Custom ButtonStyle that handles background, border, and press animation.
private struct AppButtonStyle: ButtonStyle {
    let variant: AppButtonVariant
    let isDisabled: Bool

    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .background(backgroundColor)
            .foregroundColor(foregroundColor)
            .cornerRadius(AppRadius.md)
            .overlay(borderOverlay)
            .scaleEffect(configuration.isPressed && !isDisabled ? 0.97 : 1.0)
            .animation(.easeInOut(duration: 0.1), value: configuration.isPressed)
    }

    private var backgroundColor: Color {
        switch variant {
        case .primary:     return Color.primary
        case .secondary:   return .clear
        case .ghost:       return .clear
        case .destructive: return Color.danger
        }
    }

    private var foregroundColor: Color {
        switch variant {
        case .primary, .destructive: return Color.textOnPrimary
        case .secondary, .ghost:     return Color.primary
        }
    }

    @ViewBuilder
    private var borderOverlay: some View {
        if variant == .secondary {
            RoundedRectangle(cornerRadius: AppRadius.md)
                .strokeBorder(Color.primary, lineWidth: 1.5)
        }
    }
}

// MARK: - Previews

struct AppButton_Previews: PreviewProvider {
    static var previews: some View {
        VStack(spacing: AppSpacing.md) {
            AppButton(label: "Save changes", action: {})
            AppButton(label: "Cancel", variant: .secondary, action: {})
            AppButton(label: "Learn more", variant: .ghost, action: {})
            AppButton(label: "Delete account", variant: .destructive, action: {})
            AppButton(label: "Saving", isLoading: true, action: {})
            AppButton(label: "Not available", isDisabled: true, action: {})
        }
        .padding()
    }
}

/*
 * Usage Examples:
 *
 * // Primary (default)
 * AppButton(label: "Save changes", action: handleSave)
 *
 * // Secondary
 * AppButton(label: "Cancel", variant: .secondary, action: handleCancel)
 *
 * // Destructive with accessibility hint
 * AppButton(
 *     label: "Delete account",
 *     variant: .destructive,
 *     action: handleDelete,
 *     accessibilityHint: "Permanently deletes your account and all data"
 * )
 *
 * // Loading state
 * AppButton(label: "Saving", isLoading: isSaving, action: handleSave)
 *
 * // Large size
 * AppButton(label: "Get started", size: .lg, action: handleStart)
 */
