/// AppButton — Flutter
///
/// Generated by /generate-component using the project's design token system.
/// Platform: Flutter (Dart)
/// Tokens: lib/tokens.dart

import 'package:flutter/material.dart';
import '../tokens.dart';

/// Visual style variants for [AppButton].
enum AppButtonVariant {
  /// The primary action on a screen — use once per context.
  primary,

  /// Supporting action with outlined appearance.
  secondary,

  /// Tertiary action; no background or border.
  ghost,

  /// Irreversible or dangerous action (delete, remove, clear).
  destructive,
}

/// Size options for [AppButton].
enum AppButtonSize { sm, md, lg }

/// A design-system-aware button component for Flutter.
///
/// All colors, spacing, and radii come from the token system.
/// Pass `onPressed: null` to disable the button.
class AppButton extends StatelessWidget {
  /// Visible label text. Also used as the semantic label for screen readers.
  final String label;

  /// Tap handler. Pass `null` to disable the button.
  final VoidCallback? onPressed;

  /// Visual style variant. Defaults to [AppButtonVariant.primary].
  final AppButtonVariant variant;

  /// Size of the button. Defaults to [AppButtonSize.md].
  final AppButtonSize size;

  /// When `true`, replaces the label with a circular progress indicator.
  final bool isLoading;

  const AppButton({
    super.key,
    required this.label,
    required this.onPressed,
    this.variant = AppButtonVariant.primary,
    this.size = AppButtonSize.md,
    this.isLoading = false,
  });

  @override
  Widget build(BuildContext context) {
    final bool isDisabled = onPressed == null || isLoading;

    return Semantics(
      label: label,
      button: true,
      enabled: !isDisabled,
      child: ConstrainedBox(
        // Minimum touch target: 48×48dp (Material Design)
        constraints: const BoxConstraints(minWidth: 48, minHeight: 48),
        child: _buildVariant(context, isDisabled),
      ),
    );
  }

  Widget _buildVariant(BuildContext context, bool isDisabled) {
    final EdgeInsets contentPadding = _resolvePadding();
    final Widget content = _buildContent(context);
    final BorderRadius borderRadius = BorderRadius.circular(AppRadius.md);

    switch (variant) {
      case AppButtonVariant.primary:
        return ElevatedButton(
          onPressed: isDisabled ? null : onPressed,
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.primary,
            disabledBackgroundColor: AppColors.primary.withOpacity(0.4),
            foregroundColor: Colors.white,
            padding: contentPadding,
            shape: RoundedRectangleBorder(borderRadius: borderRadius),
            elevation: 2,
          ),
          child: content,
        );

      case AppButtonVariant.secondary:
        return OutlinedButton(
          onPressed: isDisabled ? null : onPressed,
          style: OutlinedButton.styleFrom(
            foregroundColor: AppColors.primary,
            disabledForegroundColor: AppColors.primary.withOpacity(0.4),
            side: BorderSide(
              color: isDisabled
                  ? AppColors.primary.withOpacity(0.4)
                  : AppColors.primary,
              width: 1.5,
            ),
            padding: contentPadding,
            shape: RoundedRectangleBorder(borderRadius: borderRadius),
          ),
          child: content,
        );

      case AppButtonVariant.ghost:
        return TextButton(
          onPressed: isDisabled ? null : onPressed,
          style: TextButton.styleFrom(
            foregroundColor: AppColors.primary,
            disabledForegroundColor: AppColors.primary.withOpacity(0.4),
            padding: contentPadding,
            shape: RoundedRectangleBorder(borderRadius: borderRadius),
          ),
          child: content,
        );

      case AppButtonVariant.destructive:
        return ElevatedButton(
          onPressed: isDisabled ? null : onPressed,
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.danger,
            disabledBackgroundColor: AppColors.danger.withOpacity(0.4),
            foregroundColor: Colors.white,
            padding: contentPadding,
            shape: RoundedRectangleBorder(borderRadius: borderRadius),
            elevation: 2,
          ),
          child: content,
        );
    }
  }

  Widget _buildContent(BuildContext context) {
    if (isLoading) {
      final Color indicatorColor =
          (variant == AppButtonVariant.primary || variant == AppButtonVariant.destructive)
              ? Colors.white
              : AppColors.primary;
      return SizedBox(
        width: 20,
        height: 20,
        child: CircularProgressIndicator(
          strokeWidth: 2.0,
          valueColor: AlwaysStoppedAnimation<Color>(indicatorColor),
        ),
      );
    }

    return Text(label, style: _resolveTextStyle());
  }

  EdgeInsets _resolvePadding() {
    switch (size) {
      case AppButtonSize.sm:
        return EdgeInsets.symmetric(
          horizontal: AppSpacing.sm,
          vertical: AppSpacing.xs,
        );
      case AppButtonSize.md:
        return EdgeInsets.symmetric(
          horizontal: AppSpacing.md,
          vertical: AppSpacing.sm,
        );
      case AppButtonSize.lg:
        return EdgeInsets.symmetric(
          horizontal: AppSpacing.lg,
          vertical: AppSpacing.md,
        );
    }
  }

  TextStyle _resolveTextStyle() {
    final double fontSize = switch (size) {
      AppButtonSize.sm => AppTextStyles.bodySmall.fontSize ?? 13,
      AppButtonSize.md => AppTextStyles.body.fontSize ?? 16,
      AppButtonSize.lg => AppTextStyles.heading.fontSize ?? 18,
    };
    return TextStyle(fontSize: fontSize, fontWeight: FontWeight.w600);
  }
}

/*
 * Usage Examples:
 *
 * // Primary (default)
 * AppButton(
 *   label: 'Save changes',
 *   onPressed: handleSave,
 * )
 *
 * // Secondary
 * AppButton(
 *   label: 'Cancel',
 *   variant: AppButtonVariant.secondary,
 *   onPressed: handleCancel,
 * )
 *
 * // Destructive
 * AppButton(
 *   label: 'Delete account',
 *   variant: AppButtonVariant.destructive,
 *   onPressed: handleDelete,
 * )
 *
 * // Disabled (pass null to onPressed)
 * AppButton(
 *   label: 'Not available',
 *   onPressed: null,
 * )
 *
 * // Loading state
 * AppButton(
 *   label: 'Saving...',
 *   isLoading: isSaving,
 *   onPressed: handleSave,
 * )
 */
