/**
 * AppButton — React Native
 *
 * Generated by /generate-component using the project's design token system.
 * Platform: React Native (TypeScript)
 * Tokens: src/tokens.ts
 */

import React from 'react';
import {
  Pressable,
  Text,
  StyleSheet,
  Platform,
  ActivityIndicator,
  PressableProps,
} from 'react-native';
import { colors, spacing, typography, radius } from '../tokens';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'destructive';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface AppButtonProps extends Omit<PressableProps, 'style'> {
  /** Visible label text. Also used as the VoiceOver/TalkBack accessible label. */
  label: string;
  /** Press handler. */
  onPress: () => void;
  /** Visual style of the button. @default 'primary' */
  variant?: ButtonVariant;
  /** Size of the button. @default 'md' */
  size?: ButtonSize;
  /** Disables interaction and applies muted appearance. @default false */
  disabled?: boolean;
  /** Replaces label with a spinner. Button remains non-interactive. @default false */
  loading?: boolean;
  /** Optional screen-reader hint read after a pause following the label. */
  accessibilityHint?: string;
}

export function AppButton({
  label,
  onPress,
  variant = 'primary',
  size = 'md',
  disabled = false,
  loading = false,
  accessibilityHint,
  ...rest
}: AppButtonProps) {
  const isInactive = disabled || loading;

  return (
    <Pressable
      onPress={onPress}
      disabled={isInactive}
      accessibilityLabel={label}
      accessibilityRole="button"
      accessibilityState={{ disabled: isInactive }}
      accessibilityHint={accessibilityHint}
      style={({ pressed }) => [
        styles.base,
        styles[variant],
        styles[size],
        pressed && !isInactive && styles.pressed,
        isInactive && styles.inactive,
      ]}
      {...rest}
    >
      {loading ? (
        <ActivityIndicator
          size="small"
          color={
            variant === 'primary' || variant === 'destructive'
              ? colors.textOnPrimary
              : colors.primary
          }
          accessibilityLabel="Loading"
        />
      ) : (
        <Text
          style={[
            styles.label,
            styles[`${variant}Label` as keyof typeof styles],
            styles[`${size}Label` as keyof typeof styles],
          ]}
          numberOfLines={1}
        >
          {label}
        </Text>
      )}
    </Pressable>
  );
}

const styles = StyleSheet.create({
  // Base
  base: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: radius.md,
    // Minimum touch target (Apple HIG: 44pt, Material: 48dp)
    minHeight: 44,
    minWidth: 44,
    // Platform-appropriate shadow
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.12,
        shadowRadius: 3,
      },
      android: {
        elevation: 2,
      },
    }),
  },

  // Variants — background
  primary: {
    backgroundColor: colors.primary,
  },
  secondary: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.primary,
    // Shadows don't apply to transparent backgrounds
    ...Platform.select({ ios: { shadowOpacity: 0 }, android: { elevation: 0 } }),
  },
  ghost: {
    backgroundColor: 'transparent',
    ...Platform.select({ ios: { shadowOpacity: 0 }, android: { elevation: 0 } }),
  },
  destructive: {
    backgroundColor: colors.danger,
  },

  // Sizes — padding
  sm: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  md: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  lg: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },

  // States
  pressed: {
    opacity: 0.75,
  },
  inactive: {
    opacity: 0.4,
  },

  // Label base
  label: {
    fontWeight: typography.fontWeight.semibold as '600',
  },

  // Variant labels — text color
  primaryLabel: {
    color: colors.textOnPrimary,
  },
  secondaryLabel: {
    color: colors.primary,
  },
  ghostLabel: {
    color: colors.primary,
  },
  destructiveLabel: {
    color: colors.textOnPrimary,
  },

  // Size labels — font size
  smLabel: {
    fontSize: typography.fontSize.sm,
  },
  mdLabel: {
    fontSize: typography.fontSize.base,
  },
  lgLabel: {
    fontSize: typography.fontSize.lg,
  },
});

/*
 * Usage Examples:
 *
 * // Primary (default)
 * <AppButton label="Save changes" onPress={handleSave} />
 *
 * // Secondary
 * <AppButton label="Cancel" variant="secondary" onPress={handleCancel} />
 *
 * // Destructive action
 * <AppButton
 *   label="Delete account"
 *   variant="destructive"
 *   onPress={handleDelete}
 *   accessibilityHint="Permanently deletes your account and all data"
 * />
 *
 * // Loading state
 * <AppButton label="Saving" loading={isSaving} onPress={handleSave} />
 *
 * // Large size
 * <AppButton label="Get started" size="lg" onPress={handleStart} />
 */
